version: '3'

services:
    web:
        build: web/.
        command: python -u app.py
        ports:
            - "5001:5000"
        depends_on:
            - mymongodb
        environment:
            MONGODB_HOSTNAME: mymongodb
        volumes:
          - type: bind
            source: web/
            target: /app
    mymongodb:
        image: mongo:5.0.5
      # ports:
      #     - "5001:27017"
